// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// flagTypes is an autogenerated mock type for the flagTypes type
type flagTypes struct {
	mock.Mock
}

type mockConstructorTestingTnewFlagTypes interface {
	mock.TestingT
	Cleanup(func())
}

// newFlagTypes creates a new instance of flagTypes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newFlagTypes(t mockConstructorTestingTnewFlagTypes) *flagTypes {
	mock := &flagTypes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
