// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Joinables is an autogenerated mock type for the Joinables type
type Joinables struct {
	mock.Mock
}

// String provides a mock function with given fields:
func (_m *Joinables) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewJoinables interface {
	mock.TestingT
	Cleanup(func())
}

// NewJoinables creates a new instance of Joinables. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJoinables(t mockConstructorTestingTNewJoinables) *Joinables {
	mock := &Joinables{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
