// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NonFileWriter is an autogenerated mock type for the NonFileWriter type
type NonFileWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: p
func (_m *NonFileWriter) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNonFileWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewNonFileWriter creates a new instance of NonFileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNonFileWriter(t mockConstructorTestingTNewNonFileWriter) *NonFileWriter {
	mock := &NonFileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
