// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// stringer is an autogenerated mock type for the stringer type
type stringer struct {
	mock.Mock
}

type mockConstructorTestingTnewStringer interface {
	mock.TestingT
	Cleanup(func())
}

// newStringer creates a new instance of stringer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newStringer(t mockConstructorTestingTnewStringer) *stringer {
	mock := &stringer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
